import Link from "next/link"

export default function AdminDashboard() {
  return (
    <main className="max-w-6xl mx-auto px-4 py-10">

      <h1 className="text-3xl font-bold mb-8">
        Admin Dashboard
      </h1>

      <div className="grid md:grid-cols-3 gap-6">

        {/* Master Schemes */}

        <Link
          href="/admin/master-schemes"
          className="border rounded p-6 block hover:bg-gray-50"
        >
          <h2 className="text-xl font-semibold mb-2">
            Master Schemes
          </h2>

          <p className="text-gray-600">
            Create and manage master schemes used for teacher documents.
          </p>
        </Link>

        {/* Teachers */}

        <Link
          href="/admin/teachers"
          className="border rounded p-6 block hover:bg-gray-50"
        >
          <h2 className="text-xl font-semibold mb-2">
            Teachers
          </h2>

          <p className="text-gray-600">
            View and manage all registered teachers.
          </p>
        </Link>

        {/* Generated Documents */}

        <Link
          href="/admin/documents"
          className="border rounded p-6 block hover:bg-gray-50"
        >
          <h2 className="text-xl font-semibold mb-2">
            Generated Documents
          </h2>

          <p className="text-gray-600">
            View documents generated by teachers.
          </p>
        </Link>

        {/* Payments */}

        <Link
          href="/admin/payments"
          className="border rounded p-6 block hover:bg-gray-50"
        >
          <h2 className="text-xl font-semibold mb-2">
            Payments
          </h2>

          <p className="text-gray-600">
            Monitor subscriptions and document payments.
          </p>
        </Link>

        {/* System Settings */}

        <Link
          href="/admin/settings"
          className="border rounded p-6 block hover:bg-gray-50"
        >
          <h2 className="text-xl font-semibold mb-2">
            System Settings
          </h2>

          <p className="text-gray-600">
            Configure subjects, pricing and system behaviour.
          </p>
        </Link>

      </div>

    </main>
  )
}